// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package query

import (
	"context"
)

type Querier interface {
	// sql/queries/users.sql
	CreateUser(ctx context.Context, db DBTX, arg *CreateUserParams) error
	GetUserByEmail(ctx context.Context, db DBTX, email string) (*User, error)
	GetUserByID(ctx context.Context, db DBTX, id string) (*User, error)
	UpdateUser(ctx context.Context, db DBTX, arg *UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
